// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnblwqxjsbabcjulgxti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuYmx3cXhqc2JhYmNqdWxneHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTAxNzcsImV4cCI6MjA2NjkyNjE3N30.ArX-mbHelUS2xb14IqOq1KVkhvJHc5IKnOngzq6FEGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});